config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources :kittens
root 'kittens#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
end
end
  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = 'Kitten was successfully created! Meow!'
      redirect_to @kitten
    else
      flash.now[:error] = 'Oops! There was an error creating the kitten. Please check your form.'
      render :new
    end
  end

  def update
    if @kitten.update(kitten_params)
      flash[:success] = 'Kitten was successfully updated! Purrrfect!'
      redirect_to @kitten
    else
      flash.now[:error] = 'Uh-oh! There was an error updating the kitten. Please check your form.'
      render :edit
    end
  end

  def destroy
    @kitten.destroy
    flash[:success] = 'Kitten was successfully deleted! Goodbye, little one.'
    redirect_to kittens_url
  end

  private
  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<h1><%= action_name.capitalize %> Kitten</h1>

<%= form_with(model: @kitten) do |form| %>
  <% if @kitten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
        <% @kitten.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :cuteness %>
    <%= form.number_field :cuteness %>
  </div>

  <div>
    <%= form.label :softness %>
    <%= form.number_field :softness %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Delete', @kitten, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', kittens_path %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<%= link_to 'New Kitten', new_kitten_path %>

<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten %>
      <%= link_to 'Edit', edit_kitten_path(kitten) %>
      <%= link_to 'Delete', @kitten, method: :delete, data: { confirm: 'Are you sure?' } %> |
    </li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1><%= action_name.capitalize %> Kitten</h1>

<%= form_with(model: @kitten) do |form| %>
  <% if @kitten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
        <% @kitten.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :cuteness %>
    <%= form.number_field :cuteness %>
  </div>

  <div>
    <%= form.label :softness %>
    <%= form.number_field :softness %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

<%= link_to 'Edit', edit_kitten_path(@kitten) %> |
<%= link_to 'Delete', @kitten, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Awesome Kitten App</title>
    <!-- Your head content -->
  </head>
  <body>
    <% flash.each do |type, message| %>
      <div class="flash <%= type %>">
        <%= message %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>